# Generated by Django 4.1.2 on 2022-10-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_user_alter_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
    ]
