# Generated by Django 4.1.2 on 2022-10-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
    ]
