# Generated by Django 4.1.2 on 2022-10-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_song_album_album_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
