# Generated by Django 4.1.2 on 2022-10-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_album_image_image_title_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
