# Generated by Django 4.1.2 on 2022-10-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_remove_album_image_remove_user_birthday_album_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('album', models.ManyToManyField(related_name='songs', to='music.album')),
            ],
        ),
    ]
