# Generated by Django 4.1.2 on 2022-10-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song',
        ),
    ]
