# Generated by Django 4.1.2 on 2022-10-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_remove_album_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(related_name='albums', to='music.song'),
        ),
    ]
