# Generated by Django 4.1.2 on 2022-10-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_remove_album_artist_compendium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_compendium',
            new_name='albums',
        ),
    ]
