# Generated by Django 4.1.2 on 2022-10-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_rename_artist_compendium_artist_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='music.artist'),
        ),
    ]
