# Generated by Django 4.1.2 on 2022-10-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_remove_album_artists_remove_album_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='music.artist'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
