# Generated by Django 4.1.2 on 2022-10-24 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_album_artists_remove_album_artist_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
    ]
