# Generated by Django 4.1.2 on 2022-10-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
